### ISSUE TITLE
不能切换服务器的地址吗？

### ISSUE THREAD

**Issue by 931743010** [yuenov/reader-api#2]
抓取小说的地址不能进行配置吗？ 怎么配置呢

**Comment by yuenov** [comment]
数据源都是服务端全网搜索，在线转码的。不存在配置小说地址的功能。

**Comment by 931743010** [comment]
就是说离开了 yuenov.com 这个客户端就是空壳了；如果服务器坏啦；就什么都不是了呀

**Comment by yuenov** [comment]
不是所有人都会配置，应用能做的就是不让用户多做任何操作。搜索就能看，把所有的工作都放在服务端。云服务器不会坏掉的。

**Comment by yuenov** [comment]
不是所有人都会配置，应用能做的就是不让用户多做任何操作。搜索就能看，把所有的工作都放在服务端。云服务器不会坏掉的。
